data:
  name: MVTec #MVtec #VisA #AeBAD
  data_dir: datasets/MVTec
  category: screw #
                  #
  image_size: 256
  batch_size: 16
  test_batch_size: 16
  mask: True


model:
  num_workers: 2
  pretrained_model: 'vit_base'
  patch_size: 16